### ISSUE TITLE
cd /lib;./make.sh error

### ISSUE THREAD

**Issue by zhangtao22** [xieyufei1993/InceptText-Tensorflow#7]
/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1265): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this
lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1270): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
why?

**Comment by FakerYFX** [comment]
what is your gcc version and python version?

**Comment by zhangtao22** [comment]
中间有两个编译依赖错误，我都解决了，最后编译出来了，报了一个这个错误
tensorflow.python.framework.errors_impl.NotFoundError: /home/zhangtao/work/InceptText-Tensorflow/lib/deform_conv_layer/deform_conv.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by FakerYFX** [comment]
just follow this one CharlesShang/TFFRCNN#108

**Comment by zhangtao22** [comment]
我这边是gcc5，是把下边注释打开，把上边注释掉是吧，Python是2.7
## if you install tf using already-built binary, or gcc version 4.x, uncomment the two lines be    low
  g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
          roi_pooling_op.cu.o -I $TF_INC -I $NSYNC_INC -fPIC -D GOOGLE_CUDA -lcudart -L $CUDA_HOM    E/lib64 -L $TF_LIB -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0
 
  # for gcc5-built tf
  # g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
 #       roi_pooling_op.cu.o -I $TF_INC -I $NSYNC_INC -fPIC -D GOOGLE_CUDA -lcudart -L $CUDA_HOM    E/lib64 -L $TF_LIB -ltensorflow_framework  -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by FakerYFX** [comment]
yes,have a try

**Comment by zhangtao22** [comment]
试了，把所有gcc5打开，上边的注释掉，还是这个错误tensorflow.python.framework.errors_impl.NotFoundError: /home/zhangtao/work/InceptText-Tensorflow/lib/deform_conv_layer/deform_conv.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by FakerYFX** [comment]
follow this One https://github.com/Zardinality/TF_Deformable_Net

**Comment by zhangtao22** [comment]
感觉除了降gcc g++版本没有其他办法了

**Comment by ghost** [comment]
@zhangtao22  请问除了去gcc5相关掉注释，还用改其他值吗？我报错跟你不一样。

**4 errors detected in the compilation of "/tmp/tmpxft_00005a43_000000007_deform_psroi_pooling_op_gpu.cu.cpp1.ii".
g++: error: deform_psroi_pooling_op.cu.o: No such file or directory**

undefined symbol: _ZTIN10tensorflow8OpKernelE**

**Comment by zhangtao22** [comment]
你这个问题我没有遇到过啊

**Comment by ccnankai** [comment]
@zhangtao22  好吧 我搞了三天，放弃了。

**Comment by ghost** [comment]
好吧，谢谢。

**Comment by FakerYFX** [comment]
have you solved your problem when change the gcc version @zhangtao22

**Comment by zhangtao22** [comment]
@xieyufei1993 没有

**Comment by FakerYFX** [comment]
the error is what?

**Comment by zhangtao22** [comment]
还是解决不了啊

**Comment by ghost** [comment]
我都按照github上面的答案，试了个遍，没解决。

**Comment by zhangtao22** [comment]
@ccnankai 你也是用的gcc5嘛？

**Comment by zhangtao22** [comment]
我现在用虚拟机里面gcc4.9编译出来的deform_psroi_pooling.so替换了原来的同名库，还是有这个错误
undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by ghost** [comment]
@zhangtao22   4.9  5.4 我都用了，不行。服了

**Comment by FakerYFX** [comment]
try this One 
![image](https://user-images.githubusercontent.com/19235054/46252023-efab8780-c494-11e8-93bf-a6caf366c879.png)
I also meet this error before

**Comment by ghost** [comment]
@xieyufei1993   Thank you for your advice .  use the command pip install tensorflow-gpu==1.3   or  compile tensorflow  source code ?

**Comment by FakerYFX** [comment]
just use the command pip install tensorflow-gpu==1.3

**Comment by ghost** [comment]
I just come back to class, thank you for your advice .

**Comment by zhangtao22** [comment]
我执行了pip install tensorflow-gpu==1.3.0 --user，然后进入lib文件夹下make，出现/usr/bin/ld: cannot find -ltensorflow_framework

**Comment by ghost** [comment]
@zhangtao22   设这个问题。各种我都试了  跑不起来  问题出在
“nvcc -std=c++11 -c -o deform_psroi_pooling_op.cu.o deform_psroi_pooling_op_gpu.cu.cc  -I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -D GOOGLE_CUDA -arch=$ARCH“”
不能生成deform_psroi_pooling_op.cu.o
弄了好多天 ，哎

**Comment by zhangtao22** [comment]
@ccnankai 你解决了吗？怎么解决的？

**Comment by ghost** [comment]
@zhangtao22   没解决 ，所有环境我都试了，换了机器都不行，只编译通过TFFRCNN     我没查到解决方法。

**Comment by ghost** [comment]
@zhangtao22   这篇论文泛化能力强吗？能检测较长的文字行吗？ 效果不咋样的话，我就放弃了

**Comment by zhangtao22** [comment]
应该可以吧，我还没有试。其他人什么环境，都是怎么编译过的

**Comment by zhangtao22** [comment]
@ccnankai 应该可以吧，我还没有试。你现在gcc，g++，tensorflow都是什么版本，什么问题

**Comment by ghost** [comment]
@zhangtao22   好像跟g++版本没什么关系   tensorflow 1.0  1.3  1.4  1.11我都试了     都是can't find  deform_psroi_pooling_op.cu.o      你这个问题  /usr/bin/ld: cannot find -ltensorflow_framework     1.4以上版本就没有了

**Comment by zhangtao22** [comment]
@ccnankai 是的啊，我用tensorflow-gpu==1.3.0就有这个问题，你用的tensorflow是哪个版本？出现过我这个问题嘛？是怎么解决的

**Comment by zhangtao22** [comment]
@ccnankai 我用tf-gpu 1.4没有出现你说这个问题

**Comment by ccnankai** [comment]
@你cuda 和 cudnn gcc版本是什么？   我cudnn一直都是5  没换6

**Comment by zhangtao22** [comment]
@ccnankai cuda是8，cudnn是6，这两我一直没有换过

**Comment by zhangtao22** [comment]
@ccnankai 作者不是让你换tf-gpu 1.3嘛

**Comment by ghost** [comment]
我用tensorflow1.3也有这个问题，TF_Deformable_Net 上面要求1.4  
我换了1.3之后也有  can't find deform_psroi_pooling_op.cu.o     我现在重新在docker 上跑下， 环境都搞乱了。

**Comment by zhangtao22** [comment]
@ccnankai 你用1.3的时候我那个cannot find -ltensorflow_framework你是咋解决的啊？

**Comment by ccnankai** [comment]
@zhangtao22   没解决。。。

**Comment by zhangtao22** [comment]
@ccnankai 谢谢

**Comment by zhangtao22** [comment]
@xieyufei1993 你用的tensorflow-gpu，cuda，还有gcc，g++都是什么版本啊

**Comment by FakerYFX** [comment]
tensorflow_gpu==1.3 cuda8.0 gcc4.9

**Comment by ccnankai** [comment]
tensorflow_gpu==1.3 cuda8.0

![default](https://user-images.githubusercontent.com/33537489/46722227-9965f200-cca7-11e8-9dc7-3b24d80bad91.png)

**Comment by ccnankai** [comment]
@zhangtao22  我编译过了 还有其它错误，不止一个

**Comment by ghost** [comment]
@zhangtao22  我编译通过了，然后各种问题

**Comment by ghost** [comment]
@xieyufei1993  你好，请问inceptext效果怎么样啊？能定位长的文字吗？ 你那儿有效果图吗？

**Comment by ElagJun** [comment]
@zhangtao22 @ccnankai 请问你们解决了吗？我编译时没有报错，train 时报`Traceback (most recent call last):
  File "train_main.py", line 19, in <module>
    import model
  File "/data1/users/elag/github/InceptText-Tensorflow/model.py", line 11, in <module>
    from lib.deform_conv_layer.deform_conv_op import deform_conv_op
  File "/data1/users/elag/github/InceptText-Tensorflow/lib/deform_conv_layer/deform_conv_op.py", line 8, in <module>
    _deform_conv_module = tf.load_op_library(filename)
  File "/home/elag/.virtualenvs/py35env/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/elag/.virtualenvs/py35env/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /data1/users/elag/github/InceptText-Tensorflow/lib/deform_conv_layer/deform_conv.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
`
